fail_fast: true
minimum_pre_commit_version: '1.16.1'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.1
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=400']
            exclude: \.ipynb$
          - id: check-ast
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: debug-statements
          - id: fix-encoding-pragma
          - id: trailing-whitespace
    - repo: local
      hooks:
          - id: jupyter-clean
            name: jupyter-clean
            entry: clean_ipynb --no-py --no-autoflake --keep-output
            language: system
            files: \.ipynb$
          - id: init-clean
            name: init-clean
            entry: clean_ipynb --no-autoflake
            language: system
            files: \__init__.py$
          - id: python-clean
            name: python-clean
            entry: clean_ipynb --no-ipynb
            language: system
            files: \.py$
            exclude: \__init__.py$
          - id: pytest
            name: pytest
            entry: pytest -v -rs -m "not slow"
            pass_filenames: false
            language: system
            verbose: true
