language: python
python:
    - "3.7"
    - "3.8"
before_install:
    - python --version
    - pip install -U pip
install: pip install -e ".[test]"
script: pytest --cov-report=xml
after_success: bash <(curl -s https://codecov.io/bash)
